mysite/blog/urls.py
from django.urls import path

from .views import post_comment, post_detail, post_list, post_share

app_name = 'blog'

urlpatterns = [
    # path('', PostListView.as_view(), name='post_list'),
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path(
        # Форматируем урлы, что бы каждый пост имел индидуальную ссылку
        # в виде параметров: год\месяц\день\слаг-поста
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        post_detail,
        name='post_detail'
    ),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('<int:post_id>/comment/', post_comment, name='post_comment'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

mysite/blog/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    """Модельный менеджер, для того что бы упростить извлечение
    объектов из БД по полю статуса Опубликованые."""

    def get_queryset(self):
        """Получаем кверисет подмодели Статус модели Пост."""
        return (
            super().get_queryset().filter(status=Post.Status.PUBLISHED)
        )


class Post(models.Model):
    """Модель поста с характеристиками:
    Название, слаг поста, тело поста(текст)."""
    class Status(models.TextChoices):
        """Модель статуса, отражающая является ли пост
        черновиком или опубликован."""
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=256,)
    slug = models.SlugField(
        max_length=256,
        unique_for_date='pub_date'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    body = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now,)
    created = models.DateTimeField(auto_now_add=True,)
    updated = models.DateTimeField(auto_now=True,)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )
    objects = models.Manager() # Менеджер применяемы по умолчанию
    published = PublishedManager() # Конкректно прикладной менеджер
    tags = TaggableManager() # Теги постп с помощью стороннего пакета

    class Meta:
        ordering = ['-pub_date']
        # Определяет в модели индексы БД которые могут содержать
        # одно или несколько полей в возрастающем либо убывающем порядке,
        # или функциональные выражения и функции БД.
        indexes = [
            models.Index(fields=['-pub_date']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Метод отрисовывающий детальной отображение поста
        по параметрам:
          - год, месяц, день и слаг-поста."""
        return reverse(
            'blog:post_detail',
            args=[
                self.pub_date.year,
                self.pub_date.month,
                self.pub_date.day,
                self.slug
            ]
        )


class Comment(models.Model):
    """Модель комментария с характеристиками:
    название, почта, текст, создано,
    обновлено, пост, активно."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Комментарий {self.name} поста {self.post}'

mysite/blog/forms.py
from django import forms

from .models import Comment

class EmailPostForm(forms.Form):
    """Форма для заполнения имени, 
    емейла, адреса отправки и комментариев."""

    name = forms.CharField(max_length=25,)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        # изменяем виджет явным образом
        widget=forms.Textarea
    )


class CommentForm(forms.ModelForm):
    """Форма реализующая отображения комментария
    с полями:
    названия, текста, почты."""

    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

mysite/blog/views.py
from django.db.models import Count
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag

from .forms import CommentForm, EmailPostForm
from .models import Post


#class PostListView(ListView):
#    """Представление на основе класса ListView
#    для отображения всех постов по параметрам."""
#
#    queryset = Post.published.all()
#    paginate_by = 3
#    context_object_name = 'posts'
#    template_name = 'blog/post/list.html'

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'tag': tag
        }
    )

def post_detail(request, year, month, day, post):
    """Функция детального тображения одного опубликованного поста."""

    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        # реализуем логику отображения в представлении по параметрам
        # год, меся, день, слаг-поста
        slug=post,
        pub_date__year=year,
        pub_date__month=month,
        pub_date__day=day
    )

    # Список активных комментариев в к этому посту
    comments = post.comments.filter(active=True)
    # Форма для комментирования пользователем
    form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids,
    ).exclude(id=post.id)
    similar_posts =similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-pub_date')[:4]

    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog/post/detail.html', context)

def post_share(request, post_id):
    """Функция позволяющая поделиться постом с другим человеком."""

    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    sent = False

    if request.method == 'POST':
        # Форма была передана обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Валидация пройдена
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = (
                f'{cd['name']} Рекомендовано к прочтению.'
                f'{post.title}'
            )
            message = (
                f'Прочитать {post.title} на {post_url}\n\n'
                f'{cd['name']}\" комментарии: {cd['comments']}'
            )
            send_mail(
                subject,
                message,
                'filkargin@yandex.ru',
                [cd['to']],
                fail_silently=False,
            )
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        }
    )

@require_POST
def post_comment(request, post_id):
    """Функция добавления комментария
    и рендеринга страницы коммента."""

    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    comment = None
    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в БД
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.post = post
        # Сохранить комментарий в БД
        comment.save()
    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )

mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Добавить комментарий{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Ваш комиментарий успешно добавлен.</h2>
    <p><a href="{{ post.get_absolute_url }}">Назад к посту></a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Опубликовано {{ post.pub_date }} автором {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
    <a href="{% url 'blog:post_share' post.id %}">
      Поделиться постом
    </a>
  </p>

  <h2>Схожие посты</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    Тут ещё нет схожих постов
  {% endfor %}

  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} коммент(-ов)
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Комментарий {{ forloop.counter }} {{ comment.name }} {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>Тут нет комментариев.</p>
  {% endfor %}
  {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Мой Блог{% endblock %}

{% block content %}
  <h1>Мой Блог</h1>
  {% if tag %}
    <h2>Посты с тегом {{ tag.name }}</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Теги:
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
        Опубликованое {{ post.pub_date }} автором {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Поделиться постом{% endblock %}

{% block content %}
  {% if sent %}
    <h1>Письмо успешно отправленно</h1>
    <p>
      "{{ post.title }}" было успешно отправлено {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Поделиться "{{ post.title }}" по почте</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Отправка почты">
    </form>
  {% endif %}
{% endblock %}